services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: flowable
      POSTGRES_USER: flowable
      POSTGRES_PASSWORD: flowable
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowable -d flowable"]
      interval: 5s
      timeout: 5s
      retries: 20

  flowable-rest:
    image: 192.168.1.129:5000/flowable-rest-kc:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.url: jdbc:postgresql://db:5432/flowable
      spring.datasource.username: flowable
      spring.datasource.password: flowable
      flowable.database-schema-update: "true"

      FLOWABLE_COMMON_APP_SECURITY_ENABLED: "true"
      # Keep IDM engine present for Flowable bootstrap; disable default admin/demo content.
      FLOWABLE_REST_APP_ADMIN_USER_ID: "false"
      FLOWABLE_REST_APP_CREATE_DEMO_DEFINITIONS: "false"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://192.168.1.96:8080/realms/flowable"
      # SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://192.168.1.96:8080/realms/flowable/protocol/openid-connect/certs"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_COM_EXAMPLE_FLOWABLE_SECURITY: DEBUG
      # Optional: enable TRACE to see entry point selection and matcher decisions
      # LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB: TRACE

    ports:
      - "8000:8080"
    restart: unless-stopped
